version: "3.8"
services:
  covidmap-backend:
    stdin_open: true
    restart: always
    container_name: covidmap-backend
    depends_on: 
      - covidmap-database
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - GUNICORN_CMD_ARGS=--reload
    volumes:
      - "./backend/:/app"
    ports:
      - "4250:4250"
  covidmap-frontend:
    stdin_open: true
    container_name: covidmap-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
  covidmap-database:
    image: postgres
    restart: always
    container_name: covidmap-database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=example_pass
      - POSTGRES_DB=covidmap
    
     
     
volumes:
  db-data:
